name: Rustbin Github actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master

      - name: Test upload file
        run: ./rbin.sh -f rbin.sh
